# Cloudflare Pages configuration
name = "pollinations-pitch"
compatibility_date = "2023-05-01"

# This is the key setting needed for Pages
pages_build_output_dir = "dist"

# Production deployment configuration
[env.production]
environment = "production"

# Production branch configuration - this tells wrangler which branch is production
production_branch = "1900-pitch-deck"
